# Generated by Django 5.1 on 2024-08-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_dailyweathersummary_weatherentry_delete_userinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyweathersummary',
            table='DailyWeatherSummary',
        ),
        migrations.AlterModelTable(
            name='weatherentry',
            table='WeatherEntry',
        ),
    ]
