# Generated by Django 5.1 on 2024-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_alter_dailyweathersummary_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweathersummary',
            name='max_temperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailyweathersummary',
            name='min_temperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='average_temperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
